[[team]]
id = "romaric"
avatar = "https://github.com/evoxmusic.png"
github = "https://github.com/evoxmusic"
keybase = "https://keybase.io/evoxmusic"
name = "Romaric P."
bio = """\
Romaric is a Software Engineer, and CEO at <a href=\"https://www.qovery.com\">Qovery</a>. \
He has 10+ years of experience in R&D. From the Ad-Tech to the financial industry, he has deep expertise in highly-reliable and performant systems.
"""

[[team]]
id = "pierre"
avatar = "https://github.com/deimosfr.png"
github = "https://github.com/deimosfr"
keybase = "https://keybase.io/pierre"
name = "Pierre M."
bio = """\
Pierre is an SRE, and CTO of <a href=\"https://www.qovery.com\">Qovery</a>. \
He has 15+ years of experience in R&D. From the financial to the Ad-Tech industry, \
he has a strong knowledge in distributed and highly-reliable systems. \
He's also the <a href=\"https://www.amazon.fr/MariaDB-High-Performance-Pierre-MAVRO/dp/1783981601\">MariaDB High Performance</a> book author.
"""

[[team]]
id = "patryk"
avatar = "https://github.com/pjeziorowski.png"
github = "https://github.com/pjeziorowski"
keybase = "https://keybase.io/patryk"
name = "Patryk J."
bio = """\
Patryk is an experienced Software Engineer, and a Backend Developer at <a href=\"https://www.qovery.com\">Qovery</a>. \
"""

[[team]]
id = "enzo"
avatar = "https://github.com/maclikorne.png"
github = "https://github.com/MacLikorne"
keybase = "https://keybase.io/enzo"
name = "Enzo R."
bio = """\
Enzo is a Backend Developer at <a href=\"https://www.qovery.com\">Qovery</a>. \
"""

[[team]]
id = "yann"
avatar = "https://github.com/l0ck3.png"
github = "https://github.com/l0ck3"
keybase = "https://keybase.io/l0ck3"
name = "Yann I."
bio = """\
Yann is a Developer Experience Engineer at <a href=\"https://www.qovery.com\">Qovery</a>. \
He has 15+ years of experience in development and SRE.
"""

[[team]]
id = "mehdi"
avatar = "https://github.com/sileht.png"
github = "https://github.com/sileht"
keybase = "https://keybase.io/mehdi"
name = "Mehdi A."
bio = """\
Mehdi is Senior DevOps Engineer at <a href=\"https://www.qovery.com\">Qovery</a>, with 15+ years of software \
development and managing infrastructures, Co-founder of <a href=\"https://mergify.io\">Mergify</a>, active member \
of non-profit <a href=\"https://tetaneutral.net/\">Tetaneutral.net</a> ISP and Hosting provider, and he also likes to dance on crazy swing rhythm.
"""

[[team]]
id = "thibaut_david"
avatar = "https://github.com/Stun3R.png"
github = "https://github.com/Stun3R"
keybase = "https://keybase.io/Stun3R"
name = "Thibaut David"
bio = """\
Thibaut is an experienced developer, CTO of <a href=\"https://shelt.in\">Shelt.in</a> and active Qovery contributor. \
"""

[[team]]
id = "Aggis15"
avatar = "https://github.com/Aggis15.png"
github = "https://github.com/Aggis15"
keybase = "https://keybase.io/Aggis15"
name = "Angelos Rinas"
bio = """\
Angelos is a self-taught programmer using Python, Qovery ambassador and contributor. \
"""

[[team]]
id = "james_walker"
avatar = "https://github.com/ilmiont.png"
github = "https://github.com/ilmiont"
keybase = "https://keybase.io/ilmiont"
name = "James Walker"
bio = """\
James Walker is the founder of Heron Web, a UK-based digital agency providing bespoke software development services to SMEs. \
He has experience managing complete end-to-end web development workflows with DevOps, CI/CD, Docker, and Kubernetes.
"""

[[team]]
id = "dhiraj_kumar"
avatar = "https://github.com/Qovery.png"
github = "https://github.com/dhiraj_kumar"
keybase = "https://keybase.io/dhiraj_kumar"
name = "Dhiraj Kumar"
bio = """\
Dhiraj Kumar has 10+ years of experience in Python and \
Machine learning. I specialize in Data analytics and Machine learning using python. My Primary Expertise includes Python, Flask, Django, \
Pandas, NumPy, SciKit-Learn, NLP, Docker, Machine Learning, Deep Learning, Chatbot, NLP, Spark, AWS, C#, and Azure
"""

[[team]]
id = "shingai_zivuku"
avatar = "https://github.com/Qovery.png"
github = "https://github.com/shingai_zivuku"
keybase = "https://keybase.io/shingai_zivuku"
name = "Shingai Zivuku"
bio = """\
Shingai Zivuku is a softwage engineer passionated by the cloud.
"""

[[team]]
id = "benjaminch"
avatar = "https://github.com/benjaminch.png"
github = "https://github.com/benjaminch"
keybase = "https://keybase.io/benjaminch"
name = "Benjamin Chastanier"
bio = """\
Benjamin is a senior Backend Developer at <a href=\"https://www.qovery.com\">Qovery</a>.\
"""

[[team]]
id = "jul-dan"
avatar = "https://github.com/jul-dan.png"
github = "https://github.com/jul-dan"
keybase = "https://keybase.io/jul-dan"
name = "Julien Dan"
bio = """\
Julien is a Technical Product Manager at <a href=\"https://www.qovery.com\">Qovery</a>.\
"""

[[team]]
id = "acarranoqovery"
avatar = "https://github.com/acarranoqovery.png"
github = "https://github.com/acarranoqovery"
keybase = "https://keybase.io/acarranoqovery"
name = "Alessandro Carrano"
bio = """\
Alessandro is a Lead Product Manager at <a href=\"https://www.qovery.com\">Qovery</a>.\
"""

[[team]]
id = "guillaume"
avatar = "https://github.com/guimove.png"
github = "https://github.com/guimove"
keybase = "https://keybase.io/guimove"
name = "Guillaume DA SILVA"
bio = """\
Guillaume is a Senior Cloud Architect at <a href=\"https://www.qovery.com\">Qovery</a> with extensive experience \
in cloud infrastructure and Kubernetes. He specializes in designing scalable architectures and enterprise-grade solutions.\
"""
