[[technologies]]
name = "kubernetes"
logo_path = "/img/logos/kubernetes.svg"
dark_logo_path = "/img/logos/kubernetes_white.svg"

[[technologies]]
name = "helm"
logo_path = "/img/logos/helm.svg"
dark_logo_path = "/img/logos/helm_white.svg"

[[technologies]]
name = "docker"
logo_path = "/img/logos/docker.svg"
dark_logo_path = "/img/logos/docker.svg"

[[technologies]]
name = "kotlin"
logo_path = "/img/logos/kotlin.svg"
dark_logo_path = "/img/logos/kotlin.svg"

[[technologies]]
name = "qovery"
logo_path = "/img/logos/qovery.svg"
dark_logo_path = "/img/logos/qovery.svg"

[[technologies]]
name = "posthog"
logo_path = "/img/logos/posthog.svg"
dark_logo_path = "/img/logos/posthog.svg"

[[technologies]]
name = "terraform"
logo_path = "/img/logos/terraform.svg"
dark_logo_path = "/img/logos/terraform.svg"

[[technologies]]
name = "github"
logo_path = "/img/logos/github.png"
dark_logo_path = "/img/logos/github.svg"

[[technologies]]
name = "nginx"
logo_path = "/img/logos/nginx.svg"
dark_logo_path = "/img/logos/nginx.svg"